stages:
  - check

before_script:
  - echo '[install.cache]' >~/.bunfig.toml
  - echo 'dir = "./.cache/bun/install/cache"' >>~/.bunfig.toml

# Anchors

.base-check-job: &base-check-job
  stage: check
  image: oven/bun:slim
  cache:
    key: bun-cache
    paths:
      - ./.cache/bun/install/cache
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev' || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
      when: always
    - when: never

# Jobs

# stage: check
lint:
  <<: *base-check-job
  script:
    - bun i --frozen-lockfile
    - bun run lint

# stage: check
typecheck:
  <<: *base-check-job
  script:
    - bun i --frozen-lockfile
    - bun run typecheck
